check_task:
  container:
    image: fnichol/check-shell:latest
  setup_script: apk add jq
  check_script: make check

task:
  name: profile-${PROFILE}-${DISTRO}-${VERSION}
  env:
    matrix:
      - PROFILE: base
      - PROFILE: headless
  matrix:
    - matrix:
        - env:
            matrix:
              - DISTRO: alpine
                VERSION: 3.12
              - DISTRO: arch
                VERSION: latest
              - DISTRO: centos
                VERSION: 8
              - DISTRO: ubuntu
                VERSION: 20.04
          container:
            dockerfile: support/dockerfiles/Dockerfile.$DISTRO
            docker_arguments:
              VERSION: $VERSION
        - env:
            DISTRO: macos
            VERSION: 10.15
          osx_instance:
            image: catalina-base
      run_script: ./bin/prep "--profile=$PROFILE"
    - env:
        DISTRO: freebsd
        VERSION: 12-1
        USER: jdoe
      freebsd_instance:
        image_family: ${DISTRO}-${VERSION}
      prepare_script: ./support/bin/freebsd-setup.sh "--user=$USER"
      bash_script: pkg install --yes bash
      run_script: |
        sudo --preserve-env --non-interactive --set-home "--user=$USER" \
          ./bin/prep "--profile=$PROFILE"
    - env:
        DISTRO: windows
        VERSION: servercore
        CIRRUS_SHELL: powershell
      windows_container:
        dockerfile: .ci/Dockerfile.windowsservercore
        os_version: 2019
      run_script: .\bin\prep.ps1 -Profile "$env:PROFILE"
