check_task:
  container:
    image: fnichol/check-shell:latest
  setup_script: apk add jq
  check_script: make check

task:
  env:
    matrix:
      - PROFILE: base
      - PROFILE: headless
  matrix:
    - name: profile-${PROFILE}-${DISTRO}-${VERSION}
      matrix:
        - env:
            matrix:
              - DISTRO: alpine
                VERSION: 3.12
              - DISTRO: arch
                VERSION: latest
              - DISTRO: centos
                VERSION: 8
              - DISTRO: ubuntu
                VERSION: 20.04
          container:
            dockerfile: support/dockerfiles/Dockerfile.$DISTRO
            docker_arguments:
              VERSION: $VERSION
        - env:
            DISTRO: macos
            VERSION: 10.15
          osx_instance:
            image: catalina-base
      run_script: ./bin/prep "--profile=$PROFILE"
    - name: profile-${PROFILE}-windows-servercore
      windows_container:
        dockerfile: .ci/Dockerfile.windowsservercore
        os_version: 2019
      run_script:
        - ps: .\bin\prep.ps1 -Profile "$env:PROFILE"
