ARG VERSION=latest
FROM greyltc/archlinux:$VERSION

ARG VERSION
ARG USER=jdoe
ARG GROUP=$USER

RUN pacman -Syy --noconfirm \
  && pacman -S --noconfirm sudo \
  && echo "%wheel ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/01_wheel \
  && groupadd --gid 1001 "$GROUP" \
  && useradd --create-home --shell /bin/sh --groups wheel --gid "$GROUP" --uid 1001 "$USER" \
  && echo "${USER}:${GROUP}" | chpasswd

USER ${USER}:${GROUP}
ENV USER="$USER"
WORKDIR /home/$USER

CMD ["/bin/sh", "-l"]
